### ISSUE TITLE
requirement.txt file missing

### ISSUE THREAD

**Issue by narchitect** [SiruiWang0731/Tree-species-classification#1]
@SiruiWang0731 hello, Thank your for sharing your amazing work.
I've tried to install the docker image, but there is an issue with missing "requirement.txt" file to install packages.

can you upload the requirement.txt file ?

**Comment by narchitect** [comment]
my guess for reuqriement.txt below like this.
numpy
pandas
rasterio
tqdm
requests
matplotlib
glob2
pillow
jsonpath-ng
scipy
scikit-learn
tensorflow
torch
folium
opencv-python

**Comment by SiruiWang0731** [comment]
[requirements.txt](https://github.com/SiruiWang0731/Tree-species-classification/blob/a44ac698893f0cd9d7da5bd004fae9a9709d652d/requirements.txt)
